_select_data:
aspect-ratio:
- square
- portrait
- portrat-tall
- landscape
- landscape-wide

column-sizes: 
col-6: One-Half
col-12: Full Width
col-4: One Third
col-3: One Quarter
col-6_sm-12: One Half Responsive Desktop / Stacked on Mobile
col-4_sm-12: One Half Responsive Desktop / Stacked on Mobile