seo:
  site_name: Live N Move
  title: Default SEO Title
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  bright_color: '#cddadd;'
  light-brown_color: '#b89e6f'
  dark-red_color: '#793600'
  dark-brown_color: '#695125'
  darkest-brown_color: '#493725'
  dark-blue_color: '#3a4e5d'
  blue-text_color: '#cddadd'
  light-brown-text_color: '#b89e6f'
  dark-red-text_color: '#793600'
  dark-brown-text_color: '#695125'
  darkest-brown-text_color: '#493725'
  dark-blue-text_color: '#3a4e5d'
  dark-text_color: '#3c3c41'
  medium-text_color: '#5a5a5f'
  light-text_color: '#f7f5f3'
